"""
Kare-mode assets: hand-drawn 32x32 icons and 1-bit dithered plates.

Method note
-----------
Susan Kare designed the original Macintosh icons on graph paper, filling
squares with a pink marker: a 32x32 grid, 1,024 pixels, each one toggled by
hand. Her stated principles were simplicity, clarity, and beauty, plus a
preference for cartoon forms over detailed ones -- "when you have a lot of
detail, it looks like somebody else."

The icons below are authored the same way: as literal grids of characters,
one glyph per pixel, legible in the source. `#` is ink, `.` is paper.

The photographic plates use ATKINSON DITHERING rather than Floyd-Steinberg.
Bill Atkinson wrote it for the same machine Kare was drawing for; it
propagates only 3/4 of the error, which crushes detail but keeps highlights
and shadows clean. It is the reason early Mac images look the way they do,
and it is the historically correct way to reduce these renders to 1-bit.

    python -m scripts.make_pixel_art
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from PIL import Image

OUT = Path("media/kare")

# ============================================================ 32x32 ICONS
# Each icon is 32 rows of 32 characters. Read them as pictures.

ICONS: dict[str, str] = {}

# --- Chapter 1: the reality gap. A robot arm reaching for a point it misses.
ICONS["arm"] = """
................................
................................
................................
................................
................................
................................
......########..................
.....##########.................
....####....####................
....###......###################
....###......###################
....####....####..............##
.....##########...............##
......########................##
........##....................##
........##..............########
........##..............##....##
........##..............##....##
........##..............##....##
........##..............##....##
........##..............##....##
........##..............##....##
........##..............##....##
........##......................
........##......................
......######....................
.....########...................
....##########..................
...############.................
..##############................
..##############................
................................
"""

# --- Chapter 2: tendons. An open hand, four fingers and a thumb.
#
# NOTE ON THIS ICON: the first draft was a fist with a single raised finger,
# intended as Kare's pointing "Paste" hand. Rendered at 32x32 it read
# unambiguously as an obscene gesture. Kare's own warning applies exactly --
# a symbol means what a viewer sees, not what the author intended, and the
# only way to know which you drew is to look at it. Redrawn as a flat open
# palm, which cannot be misread and suits a project about finger tendons.
ICONS["hand"] = """
................................
................................
................................
.........###.###.###.###........
.........###.###.###.###........
.........###.###.###.###........
.........###.###.###.###........
.........###.###.###.###........
.........###.###.###.###........
.........###.###.###.###........
...###...###.###.###.###........
..#####..###.###.###.###........
..######################........
..######################........
..######################........
..######################........
..######################........
..######################........
..######################........
...####################.........
....##################..........
.....################...........
......##############............
.......############.............
........##########..............
.........########...............
................................
................................
................................
................................
................................
................................
"""

# --- Chapter 3: algorithms. A pendulum -- the task both algorithms solve.
ICONS["pendulum"] = """
................................
.........################.......
.........################.......
..............####..............
..............####..............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
...............##...............
..............######............
............##########..........
..##.......############......##.
.##.......##############......##
.#........##############.......#
.##.......##############......##
..##.......############......##.
............##########..........
..............######............
................................
................................
................................
................................
................................
................................
"""

# --- Chapter 4: speed. A stopwatch -- Kare drew the Mac's "wait" watch.
ICONS["watch"] = """
................................
.............######.............
............########............
...........###....###...........
........#############...........
......#####........#####........
.....###..............###.......
....###................###......
...###..................###.....
..###....................###....
..##......................##....
.###.........##...........###...
.##..........##............##...
.##..........##............##...
.##..........##............##...
.##..........#########.....##...
.##..........##............##...
.##........................##...
.###......................###...
..##......................##....
..###....................###....
...###..................###.....
....###................###......
.....###..............###.......
......#####........#####........
........#############...........
...........###....###...........
............########............
.............######.............
................................
................................
................................
"""

# --- Chapter 5: the bug index. A beetle.
ICONS["bug"] = """
................................
....##....................##....
.....##..................##.....
......##................##......
.......##..............##.......
........##............##........
.........##..........##.........
..........############..........
.........##############.........
........################........
.......####..######..####.......
..###..####..######..####..###..
.##....##################....##.
##.....##################.....##
##.....##################.....##
.##....##################....##.
..###..##################..###..
.......##################.......
.##....##################....##.
##.....##################.....##
##.....##################.....##
.##....##################....##.
..###...################...###..
.........##############.........
..........############..........
.........##..........##.........
........##............##........
.......##..............##.......
......##................##......
.....##..................##.....
................................
................................
"""

# --- Masthead mark: a happy robot, in the spirit of the Happy Mac.
ICONS["robot"] = """
................................
..............####..............
..............####..............
..............####..............
.......################.........
.....####################.......
....######################......
....##..................##......
....##..................##......
....##...####....####...##......
....##...####....####...##......
....##..................##......
....##..................##......
....##...##........##...##......
....##....##########....##......
....##..................##......
....######################......
.....####################.......
.......################.........
....##......................##..
...####....############....####.
...####....############....####.
...####....############....####.
....##.....############.....##..
...........############.........
...........############.........
............##########..........
.............########...........
.............##....##...........
............###....###..........
............###....###..........
................................
"""

# --- A "no gap" mark: two brackets closing on each other.
ICONS["gap"] = """
................................
................................
.....####################.......
.....####################.......
.....##................##.......
.....##................##.......
.....##................##.......
.....##................##.......
.....##................##.......
................................
................................
..........##########............
.........############...........
........##..........##..........
........##..........##..........
.........############...........
..........##########............
................................
................................
.....##................##.......
.....##................##.......
.....##................##.......
.....##................##.......
.....##................##.......
.....####################.......
.....####################.......
................................
................................
................................
................................
................................
................................
"""


def parse_icon(art: str) -> np.ndarray:
    """Turn an ASCII grid into a boolean array. True = ink."""
    rows = [r for r in art.strip("\n").split("\n") if r.strip("")]
    grid = np.zeros((len(rows), max(len(r) for r in rows)), dtype=bool)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            grid[y, x] = ch == "#"
    return grid


def save_icon(grid: np.ndarray, path: Path, scale: int = 12,
              ink=(20, 18, 16), paper=(0, 0, 0), transparent=True) -> None:
    """
    Render a bitmap at integer scale with hard edges.

    Nearest-neighbour only -- any smoothing destroys the entire point. The
    pixel grid is the artwork, not a low-resolution approximation of it.
    """
    h, w = grid.shape
    if transparent:
        rgba = np.zeros((h, w, 4), dtype=np.uint8)
        rgba[grid] = (*ink, 255)
        img = Image.fromarray(rgba, "RGBA")
    else:
        rgb = np.full((h, w, 3), paper, dtype=np.uint8)
        rgb[grid] = ink
        img = Image.fromarray(rgb, "RGB")
    img = img.resize((w * scale, h * scale), Image.NEAREST)
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path)


# ============================================================ DITHERING
def atkinson_dither(img: Image.Image, width: int = 420,
                    contrast: float = 1.25, brightness: float = 1.0) -> Image.Image:
    """
    Reduce an image to 1 bit using Bill Atkinson's error-diffusion filter.

    Atkinson distributes only 6/8 of the quantisation error to neighbours:

            *   1/8 1/8
        1/8 1/8 1/8
            1/8

    Discarding a quarter of the error is why it blows out highlights and
    deepens shadows -- it trades tonal accuracy for contrast and crispness,
    which is exactly right on a 1-bit display and exactly why early Mac
    graphics look the way they do.
    """
    img = img.convert("L")
    ratio = width / img.width
    img = img.resize((width, max(1, int(img.height * ratio))), Image.LANCZOS)

    a = np.asarray(img, dtype=np.float64)
    a = (a - 128.0) * contrast + 128.0 * brightness
    h, w = a.shape

    for y in range(h):
        for x in range(w):
            old = a[y, x]
            new = 255.0 if old > 128 else 0.0
            a[y, x] = new
            err = (old - new) / 8.0
            for dx, dy in ((1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w and 0 <= ny < h:
                    a[ny, nx] += err

    return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8), "L")


def crop_to_content(img: Image.Image, pad: int = 8, thresh: int = 14) -> Image.Image:
    """
    Trim uniform background before dithering.

    MuJoCo renders sit on a large black field. Dithering that field wastes
    most of the pixel budget on nothing, and the subject ends up too small to
    read once reduced to 1 bit. Cropping first spends the resolution on the
    robot.
    """
    a = np.asarray(img.convert("L"))
    mask = a > thresh
    if not mask.any():
        return img
    ys, xs = np.where(mask)
    box = (max(0, xs.min() - pad), max(0, ys.min() - pad),
           min(img.width, xs.max() + pad), min(img.height, ys.max() + pad))
    return img.crop(box)


def dither_file(src: str | Path, dst: str | Path, *, width: int = 420,
                scale: int = 2, contrast: float = 1.25,
                brightness: float = 1.0, invert: bool = True,
                crop: bool = True) -> None:
    """
    Dither a source image and upscale with nearest-neighbour.

    `invert` defaults to True: the original Macintosh screen was black ink on
    a white field, and the inverted result is both more historically correct
    and considerably more legible than white-on-black.
    """
    img = Image.open(src)
    if img.mode == "RGBA":
        bg = Image.new("RGB", img.size, (0, 0, 0))
        bg.paste(img, mask=img.split()[3])
        img = bg
    if crop:
        img = crop_to_content(img)
    out = atkinson_dither(img, width=width, contrast=contrast, brightness=brightness)
    if invert:
        out = Image.eval(out, lambda p: 255 - p)
    out = out.resize((out.width * scale, out.height * scale), Image.NEAREST)
    Path(dst).parent.mkdir(parents=True, exist_ok=True)
    out.save(dst)
    print(f"  {Path(dst).name}  {out.width}x{out.height}")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)

    print("icons (32x32, hand-plotted):")
    for name, art in ICONS.items():
        g = parse_icon(art)
        save_icon(g, OUT / f"icon_{name}.png", scale=12, ink=(235, 232, 226))
        print(f"  icon_{name}.png  {g.shape[1]}x{g.shape[0]} grid")

    print("\n1-bit plates (Atkinson):")
    dither_file("media/s5/panda_strip.png", OUT / "dith_panda.png",
                width=680, scale=2, contrast=0.95, brightness=1.05)
    dither_file("media/s4/finger_strip.png", OUT / "dith_finger.png",
                width=680, scale=2, contrast=0.9, brightness=1.15)
    print("\ndone.")
